default:
  rspark:
    packages:
      - com.databricks:spark-csv_2.11:1.3.0
      - com.amazonaws:aws-java-sdk-pom:1.10.34
      - org.apache.hadoop:hadoop-aws:2.6.0
    install:
      dir:
    connection:
      allow_local_reconnect: FALSE
    session:
      spark.sql.codegen.wholeStage: TRUE

local:
  inherits: default
  rspark:
    sql:
      spark.sql.shuffle.partitions: !expr parallel::detectCores()
    install:
      override.hive.site: TRUE
