default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  sparklyr.sql.shuffle.partitions.local: !expr parallel::detectCores()

  # default spark packages to load
  sparklyr.defaultPackages:
    - com.databricks:spark-csv_2.11:1.3.0
    - com.amazonaws:aws-java-sdk-pom:1.10.34
    - org.apache.hadoop:hadoop-aws:2.6.0

  # additional shell, context, session and sql values
  # sparklyr.shell.*
  # sparklyr.context.*
  # sparklyr.session.*
  # sparklyr.sql.*
